[tool.poetry]
name = "Dominion API"
version = "0.1.0"
description = "An API for the game Dominion"
license = "MIT"
authors = ["Ethan Saxenian <ethansaxenian@gmail.com>"]
readme = "README.md"
repository = "https://github.com/ethansaxenian/DominionAPI"
homepage = "https://dominion-api.deta.dev/docs"

[tool.poetry.dependencies]
python = "^3.9"
fastapi = "^0.87.0"
python-dotenv = "^0.21.0"
deta = "^1.1.0"

[tool.poetry.group.dev.dependencies]
black = "^22.10.0"
flake8 = "^5.0.4"
beautifulsoup4 = "^4.11.1"
requests = "^2.28.1"
tqdm = "^4.64.1"
uvicorn = "^0.19.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
