[tool.poetry]
name = "Dominion API"
version = "0.1.0"
description = "An API for the game Dominion"
license = "MIT"
authors = ["Ethan Saxenian <ethansaxenian@gmail.com>"]
readme = "README.md"
repository = "https://github.com/ethansaxenian/DominionAPI"
homepage = "https://github.com/ethansaxenian/DominionAPI"

[tool.poetry.dependencies]
python = "^3.9"
fastapi = "^0.81.0"
uvicorn = "^0.18.2"
Markdown = "^3.4.1"
beautifulsoup4 = "^4.11.1"
requests = "^2.28.1"
python-dotenv = "^0.20.0"
SQLAlchemy = "^1.4.40"
psycopg2-binary = "^2.9.3"

[tool.poetry.dev-dependencies]
black = "^22.6.0"
flake8 = "^5.0.4"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
