from enum import Enum


class Expansion(str, Enum):
    ADVENTURES = "Adventures"
    ALCHEMY = "Alchemy"
    ALLIES = "Allies"
    BASE = "Base"
    BASE_1ST_EDITION = "Base 1st Edition"
    CORNUCOPIA = "Cornucopia"
    DARK_AGES = "Dark Ages"
    EMPIRES = "Empires"
    GUILDS = "Guilds"
    HINTERLANDS = "Hinterlands"
    INTRIGUE = "Intrigue"
    INTRIGUE_1ST_EDITION = "Intrigue 1st Edition"
    MENAGERIE = "Menagerie"
    NOCTURNE = "Nocturne"
    PLUNDER = "Plunder"
    PROMO = "Promo"
    PROSPERITY = "Prosperity"
    RENAISSANCE = "Renaissance"
    SEASIDE = "Seaside"


class CardType(str, Enum):
    ACTION = "Action"
    ALLY = "Ally"
    ARTIFACT = "Artifact"
    ATTACK = "Attack"
    AUGUR = "Augur"
    BOON = "Boon"
    CASTLE = "Castle"
    CLASH = "Clash"
    COMMAND = "Command"
    CURSE = "Curse"
    DOOM = "Doom"
    DURATION = "Duration"
    EVENT = "Event"
    FATE = "Fate"
    FORT = "Fort"
    GATHERING = "Gathering"
    HEIRLOOM = "Heirloom"
    HEX = "Hex"
    KNIGHT = "Knight"
    LANDMARK = "Landmark"
    LIAISON = "Liaison"
    LOOTER = "Looter"
    NIGHT = "Night"
    ODYSSEY = "Odyssey"
    PRIZE = "Prize"
    PROJECT = "Project"
    REACTION = "Reaction"
    RESERVE = "Reserve"
    RUINS = "Ruins"
    SHELTER = "Shelter"
    SPIRIT = "Spirit"
    STATE = "State"
    TOWNSFOLK = "Townsfolk"
    TRAVELLER = "Traveller"
    TREASURE = "Treasure"
    VICTORY = "Victory"
    WAY = "Way"
    WIZARD = "Wizard"
    ZOMBIE = "Zombie"
